=== julElliot/Lab2/target/classes/client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clients" type="clientsType"/>
    <xs:complexType name="clientType">
        <xs:sequence>
            <xs:element type="xs:integer" name="id"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="surname"/>
            <xs:element type="xs:string" name="login"/>
            <xs:element type="xs:string" name="password"/>
            <xs:element type="xs:integer" name="discount"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clientsType">
        <xs:sequence>
            <xs:element type="clientType" name="client" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== julElliot/Lab2/src/main/resources/clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xs:noNamespaceSchemaLocation="client.xsd">
    <client>
        <id>19</id>
        <name>Julia</name>
        <surname>Kozlova</surname>
        <login>Kozlova</login>
        <password>Kozlova</password>
        <discount>100000</discount>
    </client>
</clients>
